CREATE DATABASE IF NOT EXISTS log_ingestor_db;

CREATE USER IF NOT EXISTS 'root'@'localhost' IDENTIFIED BY 'root';

GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION;

FLUSH PRIVILEGES;
